### ISSUE TITLE
Формирование окружения разработчика

### ISSUE THREAD

**Issue by alehinsasha** [bwire/BigFinalTask#1]
- [x] Внешние отчеты и обработки разбираются на исходники
- [x] Структура каталогов репозитория из bootstrap

**Comment by bwire** [comment]
Тут все

**Comment by bwire** [comment]
Александр. На какой конфигурации это все делать:
 - написать свою болванку?
 - вы даете какой то каркасный шаблон?
 - использовать какую то типовую?

**Comment by alehinsasha** [comment]
Для решения используйте созданную с 0 конфигурацию.
