### ISSUE TITLE
Разработка по промышленным стандартам

### ISSUE THREAD

**Issue by alehinsasha** [bwire/BigFinalTask#3]
- [x] Одна функциональность = одна фича и сценарии проверяющие работу этой фичи/функциональности
- [x] Использование фикстур
- [x] Повторное использование шагов (собственная библиотека шагов)
- [x] Фичи из воздуха
- [x] Детализация фичи

**Comment by alehinsasha** [comment]
**В дополнение к проверке навыка "Повторное использование шагов (собственная библиотека шагов)"**

Для подтверждения этого навыка у вас должно быть:
1. Две фичи проверяющие поступление и продажу товара.
2. В каталоге features каталог в котором вы будете хранить ваши библиотечные фичи.
3. В этом каталоге библиотечных шагов должна быть одна фича с одним универсальным (параметризованным) шагом который будет удалять документы.
4. В фичах поступления и продажи нужно использовать этот библиотечный шаг.

**Comment by bwire** [comment]
Но почему то выгрузилось (разберусь позже).

**Comment by bwire** [comment]
Александр. А в каком виде должна быть собственная библиотека шагов. Нужно ли повторяющиеся процедуры сохранить отдельно, например, в bsl и выложить в какую то папку или достаточно факт использования этих процедур в разных обработках?

**Comment by alehinsasha** [comment]
> в каком виде должна быть собственная библиотека шагов?

У меня это каталог "Библиотека шагов" в каталоге features. В каталоге "Библиотека шагов" пока одна фича, и не связанные друг с другом шаги, т.к. они (шаги) все равно ж из разных фич использоваться будут.

**Comment by bwire** [comment]
Комментарий к фиче проверки партионного.

Написал самую простую версию, так как здесь проверяется не умение  архитектурить систему. Тест состоит в следующем:
 - генирится примитивный набор документов, так чтобы при продаже товара хватало;
- после загрузки документов они проводятся по порядку, при этом граница партионного уезжает на последний документ;
- перепроводится первый приход, чтобы сдвинуть границу в начало;
- запускается проведение по партиям и убеждаемся, что все хорошо;
- идем в самое первое поступление и имитируем грубое необдуманное дествие: уменьшаем поступившее количество (граница опять уезжает в начало);
- запускаем партионный опять и проверяем перехват ошибки.
В принципе весь алгоритм я вложил в текст фичи.

Александр, есть один вопрос. Надкнулся на то, что когда пишу очередную фичу, Behavior может подхватить процедуры, которых нет в обработке текущего поведения, но они подбрасываются из предыдущих обработок. Например некоторое время не мог понять, почему у меня не генеритс я процедура: СистемаВыдалаСообщениеСТекстом(). Оказалось, в шаг прописалась эта процедура, но из другой обработки. Чтобы выйти из положения, разложил фичи по отдельным каталогам - помогло. Так и задумано?

Спасибо.

**Comment by alehinsasha** [comment]
Думаю мой ответ на похожий вопрос, поможет вам разобраться: Собственная библиотека шагов строиться на функциональности "Повторное использование шагов". Например, вам нужно подготовить инфобазу для сценария, т.е. что-то удалить (изменить), создать (загрузить фикстуры). Предположим у вас две фичи, первая проверяет функциональность проведения документа "Приход", вторая - документа "Расход". И в первой и во второй нужно удалять  данные. Для этого мы можем написать шаг `Я удаляю все документа вида "<ИмяВидаДокумента>"`, и вот тут возникает вопрос - где, в какой фиче этот шаг написать? Если напишем этот шаг в фиче "Приход" и сгенерируем обработку соответствующую фиче "Приход" и в ней реализуем этот шаг то, в фиче "Расход" достаточно написать "один-в один" этот шаг, а реализация этого шага (процедура проверки этого шага) при чтении/выполнении сценария из фичи "Расход" будет взята из обработки соответствующей фиче "Приход", так работает функциональность "Повторное использование шагов". И вроде бы все ОК, но фича "Приход" проверяет конкретную бизнес-функциональность, а мы ведь можем и забыть что от нее зависит фича "Расход" и что-то исправить или удалить. Поэтому рекомендуется подобные шаги делать универсальными (использовать параметры) и выносить в отдельные фичи, кстати, совсем не обязательно чтобы в таких фичах шаги составляли какой либо логический сценарий.

**Comment by alehinsasha** [comment]
> Так и задумано?

Да, это функциональность "Повторное использование шагов".

**Comment by bwire** [comment]
Я про это подумал, но на этом шаге все ломалось, пока не разложил по каталогам.

**Comment by bwire** [comment]
Хотя, может я не прав. Скажите, обязательно ли накрутить все эти премии и зарплату сотрудникам? Думаю, что уже ничего нового в плане изложенного материалы продемонстрировать не получится.
Что еще нужно вам показать?

**Comment by bwire** [comment]
> 
Поэтому рекомендуется подобные шаги делать универсальными (использовать параметры) и выносить в отдельные фичи, кстати, совсем не обязательно чтобы в таких фичах шаги составляли какой либо логический сценарий.

А как Behavior поймет, что эти общие куски нужно взять из какого то опеределенного места?

**Comment by bwire** [comment]
Судя по всему, нужно в каталог step_definitions положить обработку ПовторныеШаги и в ней разместить все повторные шаги, а Behavior будет искать шаг по всем обработкам в этом каталоге?

**Comment by bwire** [comment]
Попробовал сделать так вынес шаг по формированию сообщения в отдельнуб обработку ПовторныеШаги, перезагрузил сценарий, но теперь все шаги, которые описаны у меня в обработке ПроведениеПоПартиям (которые я добавлял сам) система ищет в новой обработке ПовторныеШаги? :) А если мне нужен специфический шаг для данной обработки и я его не хочу использовать повторно, тогда как?

**Comment by alehinsasha** [comment]
Если шаг без параметров, то у него должна быть только одна реализация, это 100%. А вот если у шага есть параметры, то реализация (она же проверка шага) все равно должна быть одна. Исключение, когда в фиче нужно использовать макет из обработки соответствующей фиче. Но это решается методом `Ванесса.ОбработкаСвязаннаяСИсполняемойФичей.ПолучитьМакетОбработки(ИмяМакета)`.

**Comment by bwire** [comment]
У меня в обработке ПроведениеПоПартиям есть метод ЯПодготавливаюСпециальныеДанныеДляПроверки() - такого метода нет больше в других обработках - это точно. Я специально переименовывал метод, чтобы он не пересекался с методом из другой обработки. Но Behavior при перезагрузке сценария пишет обработку вызова искать в ПовторныеШаги - а в ней пока только процедура по сообщениям. Что ж не так?

**Comment by bwire** [comment]
Все понятно. В обработках ненужные шаги поубирал, но забыл про процедуры ПолучитьСписокТестов(), где тоже нужно было лишнее поубирать/ нужное добавить. Всю исправленную систему коммитнул только что.

**Comment by alehinsasha** [comment]
5+
